// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_files_quotas

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FilesQuotasResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Unique ID of this directory.",
				MarkdownDescription: "Unique ID of this directory.",
			},
			"limit": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Limit in bytes of the cumulative size of this directory and its descendants.",
				MarkdownDescription: "Limit in bytes of the cumulative size of this directory and its descendants.",
			},
		},
	}
}

type FilesQuotasModel struct {
	Id    types.String `tfsdk:"id"`
	Limit types.String `tfsdk:"limit"`
}
